server:
  port: 8081
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: "none"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/library
    username: library
    password: library
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true
    baselineOnMigrate: true
  hibernate:
    type:
      preferred_uuid_jdbc_type: "CHAR"
logging:
  level:
    root: "warn"

application:
  max-book-quantity-for-user: 10
